apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-deploy
spec:
  template:
    spec:
      containers:
        - name: mas
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: master