apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
configMapGenerator:
  - name: mas-cfg
    files:
      - spring/application.yml
    options:
      labels:
        app: master-service
