apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- github.com/tomkre/sandbox-spring-cloud/k8s?ref=master
- deployment.yml
- service.yml
patches:
- path: deployment-patch.yml
configMapGenerator:
- files:
  - spring/application.yml
  name: mas-cfg
  options:
    labels:
      app: master-service
images:
- name: master-service
  newName: tomkre/sbs-master-service
  newTag: "1.0"
replicas:
  - name: mas-deploy
    count: 2