name: Commit Stage
on: push
jobs:
  job_one:
    name: job_one
    runs-on: ubuntu-22.04
    steps:
      - name: job_one step
        run: |
          sleep 9
          echo 'Running job_one'
  job_two:
    name: job_two
    runs-on: ubuntu-22.04
    steps:
      - name: job_two step
        run: |
          sleep 9
          echo 'Running job_two'
  job_three:
    name: job_three
    runs-on: ubuntu-22.04
    steps:
      - name: job_three step
        run: |
          sleep 9
          echo 'Running job_three'
  job_four:
    name: job_four
    runs-on: ubuntu-22.04
    needs: [job_one, job_two]
    steps:
      - name: job_four step
        run: echo 'Running job_four'
