name: Commit Stage
on: push
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Payload dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: tomkre/sandbox-github-deployment
          event-type: app_delivery
          client-payload: '{
            "app_name": "github-service",
            "app_version": "1.5.0",
            "app_author": "tom"
          }'
              
