name: Foo Stage
on:
  workflow_run:
    workflows: ['Commit Stage']
    types: [completed]
    branches: [master]
jobs:
  job_one:
    name: Job one
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Job one step
        run: |
          echo 'Running job one step'
  job_two:
    name: Job two
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Job two step
        run: |
          echo 'Running job two step'
  job_three:
    name: Job three
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Job three step
        run: |
          echo 'Running job three step'              
